### ISSUE TITLE
3D heatmap and 3D keypoint

### ISSUE THREAD

**Issue by zhoujiayu-zjy** [yiyueluo/IntelligentCarpet#3]
I would like to know more about how to get 3D keypoints from 2D keypoints. Is it possible to open source the code in this area

**Comment by yiyueluo** [comment]
Given the intrinsic and extrinsic parameters of the cameras, which we obtained by using the MATLAB camera calibration toolkit, we were able to triangulate the 2D keypoints into 3D keypoints using epipolar geometry. 

Some useful information from OpenCV: https://docs.opencv.org/4.5.3/d9/d0c/group__calib3d.html
A useful function from MATLAB: https://www.mathworks.com/help/vision/ref/triangulate.html#d123e230810
