### ISSUE TITLE
singlePerson_test file is too big to be downloaded

### ISSUE THREAD

**Issue by zhaoloulou** [yiyueluo/IntelligentCarpet#6]
Hello, thank you for your work. The problem I am facing is that the singlePerson_test file can not be downloaded and the test is missing log.p file can not be run, there are other ways to download, or can provide a separate
After the singlePerson_test file are unzipped, what other files are in the folder similar to the one in the picture below
![image](https://user-images.githubusercontent.com/42457505/172125846-f5ecd7c5-bab3-49ed-b898-9eced0c54d82.png)

**Comment by yiyueluo** [comment]
There should be more folders and a log.p file. If the file is too big to download, try installing Dropbox desktop for local sync.
